### PR TITLE
Some fixes based on schtasks.exe options. 

### PR DESCRIPTION
**Pull request by elpetak**
Fixes on_idle which should be onidle in schtasks.exe command line.
Adds frequency_modifier interpretation for on_idle (/I option is required for onidle)
Fixes /MO being included in some cases when it shouldn't be.
Fixes day validation when day is a number (used in some monthly variants).
Fixes frequency_modifier validation for on_idle.

### CODE REVIEW

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.getchef.com/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## Non-GitHub Verified Committers

There are 1 commit author(s) whose commits are authored by a non-GitHub verified email address. Chef will have to manually verify that they are authorized to contribute.

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by elpetak** [comment]
To who it may concert, I did sign the CLA but I guess that having my email set to "private" in github (or not setting an email in git client) may have prevented the bot from identifying me.

**Comment by mwrock** [comment]
looks like you have a rubocop violation

**Comment by elpetak** [comment]
@mwrock it seems that way, but that line of code causing the offense is not mine, it was already there.
It comes from a 2012 commit: [736609fa9af252e19a5f41d6923608a111f936b3](https://github.com/chef-cookbooks/windows/commit/736609fa9af252e19a5f41d6923608a111f936b3)
Maybe something changed in the rubocop checks?

**Comment by mwrock** [comment]
ah ok. I'll address in a separate pr later and let you know so you can rebase on that

**Comment by elpetak** [comment]
@mwrock I've just found a bug in my proposed code. I'll cancel this pull request and will open a new one once you merge your fixes.

**Comment by mwrock** [comment]
I just merged the style fix

**Pull request closed without merging**
