### PR TITLE
fixes #324 copying font files before installing the font

### LINKED ISSUE #324: window_font resource broken?
Trying to install fonts from a cookbook as per the docs, this all I can get to:

```
  * windows_font[HackBold.ttf] action install[2016-01-06T00:00:30-05:00] INFO: Processing windows_font[HackBold.ttf] act
ion install (soundwave::default line 39)


    ================================================================================
    Error executing action `install` on resource 'windows_font[HackBold.ttf]'
    ================================================================================

    NoMethodError
    -------------
    undefined method `file' for nil:NilClass

    Resource Declaration:
    ---------------------
    # In C:/Users/sescriv2/.chef/local-mode-cache/cache/cookbooks/soundwave/recipes/default.rb

     39: windows_font "HackBold.ttf"
     40:

    Compiled Resource:
    ------------------
    # Declared in C:/Users/sescriv2/.chef/local-mode-cache/cache/cookbooks/soundwave/recipes/default.rb:39:in `from_file
'

    windows_font("HackBold.ttf") do
      action [:install]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :windows_font
      cookbook_name "soundwave"
      recipe_name "default"
      file "HackBold.ttf"
    end
```

### PR DESCRIPTION
**Pull request by mwrock**
Looks like `windows_font` is totally broken right now. This fixes it and adds a kitchen test for it.

### CODE REVIEW

**Comment by mwrock** [comment]
looks like this got broke in the last release: https://github.com/chef-cookbooks/windows/commit/c90ae7cc592736d3e02784a3b14b5797ef7bca93

**Comment by mwrock** [comment]
cc @chef-cookbooks/client-windows

**Comment by smurawski** [comment]
:+1: Yay for more kitchen tests!

**Comment by danielsdeleo** [comment]
LGTM

**Pull request merged**
