### PR TITLE
windows_http_acl in a language agnostic way using Windows-API

### PR DESCRIPTION
**Pull request by maltewitt**
### Description

Getting the current URL ACL reservations is now implemented via Windows API (using FFI). The result no longer depends on the language-specific output of netsh.exe
### Issues Resolved

https://github.com/chef-cookbooks/windows/issues/379
### Check List
- [x] All tests pass. See https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable
- [ ] The CLA has been signed. See https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD

### CODE REVIEW

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.getchef.com/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## GitHub Users Who Are Not Authorized To Contribute

The following GitHub users do not appear to have signed a CLA:

* @maltewitt

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by maltewitt** [comment]
The reason for travis-ci failing is the missing **httpapi** lib, which is part of the Windows-API and only available on windows systems. IMHO this seems to be fine for the windows cookbook. 
What is the best way to satisfy travis-ci anyways? Is there some best common practice?

**Comment by mwrock** [comment]
This is definitely the right direction here. I think you may be able to eliminate alot of the FFI mappings because many already exist in chef core. Have a look at the classes in https://github.com/chef/chef/tree/master/lib/chef/win32/api. Not all is there but probably most.

Regarding travis, typically we just dont run windows native stuff in travis. In this case it would be good to do something like this:
```
include Windows::UrlAcl if Chef::Platform.windows?
````

**Comment by tas50** [comment]
@maltewitt Can you rebase this PR?

**Comment by tas50** [comment]
Closing this out since we never heard back on the rebase. This is certainly something we'd like to take in. We've done similar conversions to FFI in the past and generally we do the FFI work in a gem, but this is part way towards that end goal.

**Pull request closed without merging**
