### PR TITLE
add compile_time false to silence annoying warnings …

### PR DESCRIPTION
**Pull request by smurawski**
… and actually read ChefSpec output

### CODE REVIEW

**Comment by smurawski** [comment]
@chef-cookbooks/client-windows and @chef-cookbooks/windows-cookbook-collaborators

**Comment by mwrock** [comment]
:+1:

**Comment by tas50** [comment]
:+1:

**Comment by Tech356** [comment]
Does the compile_time setting need to be added to the [zipfile](https://github.com/chef-cookbooks/windows/blob/0d709c348b0cfd1cb3f7885873e7513817a4df74/providers/zipfile.rb#L86-L89) provider?

**Comment by mwrock** [comment]
Yeah. it should.

**Pull request merged**
