### PR TITLE
Enable certificate search controls

### PR DESCRIPTION
**Pull request by xorima**
### Description

This commit will allow us to manage how certificates are found in the powershell script when binding to a port, ensures that we should always find the certificate if it exists but gives additional controls as to how to find that certificate. 

### Issues Resolved

N/A

### Check List

- [x] All tests pass. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD>
- [x] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable
- [x] All commits have been signed for the Developer Certificate of Origin. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD>

Signed-off-by: Jason Field

### CODE REVIEW

**Comment by Xorima** [comment]
Nudge, could this one be looked at some point?

**Comment by Xorima** [comment]
Can this be looked at?

**Comment by stuartpreston** [comment]
Hi @Xorima I had a quick look at this over the weekend and we have a few conflicts, mainly because @tas50 has done a great job of moving the resources from this cookbook into core Chef and hopefully there are fewer and fewer use cases for needing this cookbook at all these days.

1. Appveyor currently tests against Chef 13 (if it used Chef 14.7 or above, the integration tests would be testing the Chef resources, not the resources in the cookbook)
2. Version >6 of this cookbook requires Chef 14

From a functionality perspective the code looks good and could be merged, but it would probably be better off adding the `windows_certificate_binding` resource in its entirely to Chef 15 instead.

@tas50 any thoughts?

**Comment by tas50** [comment]
I'm closing this out at this point since we're not adding any new functionality to this cookbook.

**Pull request closed without merging**
