### PR TITLE
Font hang

### PR DESCRIPTION
**Pull request by jkburges**
### Description

[Describe what this change achieves]

### Issues Resolved

[List any existing issues this PR resolves]

### Check List

- [ ] All tests pass. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD>
- [x] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable
- [x] All commits have been signed for the Developer Certificate of Origin. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD>

### CODE REVIEW

**Comment by jkburges** [comment]
I don't _think_ the CI failure is to do with anything I have changed.

I ran:

```
chef exec kitchen test font-windows-2012r2
```

locally, and that worked.

**Comment by Xorima** [comment]
@jkburges they have commited a fix to master now which should enable builds to work, if you update master this should pass 👍

**Comment by tas50** [comment]
@jkburges This isn't something we can bring into Chef since the ttfunk gem is GPL v3. That's an incompatible licensed gem. If there's another way to accomplish this I'd gladly get it in here and into chef itself since this resource ships in Chef now.

**Comment by jkburges** [comment]
Closing due to incompatible licensed gem.

**Pull request closed without merging**
