### PR TITLE
Added support for configurable source in font LWRP

### PR DESCRIPTION
**Pull request by joemillerr**
### Description
Added support for configurable source in font LWRP.  This allows fonts to be untethered from the cookbooks they are used in when retrieving fonts from elsewhere (ex:artifact repo, file share, etc.)

Used remote_file to hold source resolution until runtime, lazy eval using the file LWRP might be considered a better option but I was not sure what is best practice in the sort of scenario.

### Issues Resolved
Issue #363

### CODE REVIEW

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.getchef.com/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## Non-GitHub Verified Committers

There are 1 commit author(s) whose commits are authored by a non-GitHub verified email address. Chef will have to manually verify that they are authorized to contribute.

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by joemillerr** [comment]
I've already signed the ICLA.

**Comment by mwrock** [comment]
would be great if you could doc the attribute in the readme and add a test to https://github.com/chef-cookbooks/windows/blob/master/test/cookbooks/minimal/recipes/font.rb and https://github.com/chef-cookbooks/windows/blob/master/test/integration/font/pester/minimal.font.Tests.ps1.

**Comment by joemillerr** [comment]
Hey Matt,
I updated the README and added a test (first time using Pester).  The kitchen build failed but it looks unrelated to what I changed.

**Comment by joemillerr** [comment]
Looking at this a bit closer, it looks like it broke in the tests for the "path" recipe.  I have tried to track down if something I changed caused this but I don't believe thats the case.

**Comment by mwrock** [comment]
I just ran both the font and path suites locally @joemillerr  and both verifications passed. This could possibly be a transient error. Try pushing an empty commit and see if it passes.

**Comment by joemillerr** [comment]
Looks like that did it.  Thanks @mwrock !

**Comment by mwrock** [comment]
awesome. This LGTM :+1:

**Pull request merged**
