### PR TITLE
Changed where clause to be PS 1.0/2.0 friendly

### PR DESCRIPTION
**Pull request by dreznicek**
The where clause searching for **subject** was not Powershell 1.0/2.0 friendly, so I converted it to the "old style".

### CODE REVIEW

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.getchef.com/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## GitHub Users Who Are Not Authorized To Contribute

The following GitHub users do not appear to have signed a CLA:

* @dreznicek

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by mwrock** [comment]
:+1:

**Comment by chef-supermarket** [comment]
Hi. Your friendly Curry bot here. Just letting you know that all commit authors have become authorized to contribute. I have added the "Signed CLA" label to this issue so it can easily be found in the future.

**Comment by chefsalim** [comment]
:+1:

**Comment by mwrock** [comment]
Thanks @dreznicek !

**Pull request merged**
