### PR TITLE
add BUILTIN\Users to SYSTEM_USERS

### PR DESCRIPTION
**Pull request by jasonwbarnett**
### Description

This adds BUILTIN\Users to SYSTEM_USERS

### Issues Resolved

N/A

### Check List

- [x] All tests pass. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD>
- [x] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable
- [x] All commits have been signed for the Developer Certificate of Origin. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD>

### CODE REVIEW

**Comment by jugatsu** [comment]
@jasonwbarnett What is the purpose to use bultin users group for scheduled task?

**Comment by smurawski** [comment]
@jugatsu it would let you schedule a task to run in the context of the logged in user, whomever that was.  It's a worthwhile addition.

**Comment by jugatsu** [comment]
@smurawski thanks for explanation

**Comment by tas50** [comment]
Thanks @jasonwbarnett

**Pull request merged**
