### PR TITLE
Require Chef 12 or later

### PR DESCRIPTION
**Pull request by tas50**
### Description

This PR deprecates support for Chef releases before Chef 12 and in doing so allows us to remove providers that are now part of core chef. That reduces the size of the cookbook and speeds up client runs.

### Issues Resolved

NA

### Check List
- [ ] All tests pass. See https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD
- [ ] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable
- [x] The CLA has been signed. See https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD

### CODE REVIEW

**Comment by btm** [comment]
Can you remove `windows_package` as well? In 2015-12 we said we would remove it in the next major release of this cookbook in 1a7ad4d402d0926078ecc196e873f5c7f6778cb2, and this looks like a major release. :)

**Comment by tas50** [comment]
@btm we still haven't added all the package types to core chef so that needs to stay. Once we do that we can wait a few years and nuke it from here ;)

**Comment by smurawski** [comment]
@tas50 Actually, I think we have moved all the package types over. (most were in https://github.com/chef/chef/pull/4193)

**Comment by btm** [comment]
Yeah, I thought we had. Can you be more specific about what you think is missing?

**Comment by tas50** [comment]
Well snap I stand corrected on the other types of packages. We still can't nuke it though since it only shipped in 12.6. There's plenty of people still rocking < 12.6 out there. Wait till it's been out for at least a year and then we can nuke it.

**Comment by tas50** [comment]
So @btm @smurawski @mwrock Any reason not to merge it?

**Comment by smurawski** [comment]
:+1:

**Comment by mwrock** [comment]
:+1:

**Pull request merged**
