### PR TITLE
[WIP]: Add support for running windows_task resource on non-English version of Windows

### PR DESCRIPTION
**Pull request by jugatsu**
### Description

Add support to `windows_task` resource to run on non-English editions of Windows.

As for now, `windows_task` resource created on every converge on non-English version of Windows, for example, Russian edition.

This is because
```ruby
def task_need_update?
    # gsub needed as schtasks converts single quotes to double quotes on creation
    current_resource.command != new_resource.command.tr("'", '"') ||
      current_resource.user != new_resource.user
  end
```
always returns that task need to update because
```ruby
output = shell_out("schtasks /Query /FO LIST /V /TN \"#{task_name}\"").stdout
```
outputs in local codepage and therefore can not be parsed successfully.

Further discussion here https://github.com/chef/chef/pull/5886

### Fixes
https://github.com/chef-cookbooks/windows/issues/462

### CODE REVIEW

**Comment by smurawski** [comment]
@jugatsu I'd love to get this PR merged, but we need the commits to have the DCO sign-off on them.  Could you squash the commits and add the sign off?

**Comment by jugatsu** [comment]
@smurawski i will as i figure it out

**Comment by smurawski** [comment]
@jugatsu If you have any questions on how, please ask.  I'd be happy to help.

**Comment by jugatsu** [comment]
@smurawski I think I completely screwed up this PR :)

Should I close this one and make seperate PR?

**Comment by jugatsu** [comment]
Closing down on flavor of https://github.com/chef-cookbooks/windows/pull/463

**Pull request closed without merging**
