### PR TITLE
added share LWRP

### PR DESCRIPTION
**Pull request by rlaveycal**
There have been 3 previous pull requests for a share LWRP (#73, #87, #135).

This is an enhancement of #73 (thanks @solvip) that makes all the properties idempotent and supports whyrun. It uses WMI via WINOLE rather than the net share command.

### CODE REVIEW

**Comment by solvip** [comment]
I'd love to see this merged!  I can't remember why I closed #73 - there must have been a reason.
Is there anything I can do to help move this forward?

**Comment by smurawski** [comment]
@rlaveycal Thanks for the submission and I'd like to get it merged (sorry for the delay in response).  It'd be really helpful to get some kitchen tests built out that exercise the resource. (@solvip you'd be welcome to contribute some tests as well to help move it along).

**Comment by rlaveycal** [comment]
@smurawski I've added some tests - first time in the Kitchen!

**Comment by tas50** [comment]
I resolved the merge conflicts and merged this in. Thanks for taking the time to put it together. Sorry it took so long to get it merged

**Pull request merged**
