### PR TITLE
Fix rubocop warnings

### PR DESCRIPTION
**Pull request by shoekstra**

### CODE REVIEW

**Comment by shoekstra** [comment]
So, wanted to start by saying this is going above and beyond to get https://github.com/chef-cookbooks/windows/pull/338 merged, :) if the foodcritic 5.0.0 was used (as is present in Chef DK 0.10.0) the style tests would pass:

```
~/c/windows ❯❯❯ chef exec foodcritic --version
foodcritic 5.0.0
~/c/windows ❯❯❯ chef exec rake style
Starting Foodcritic linting...
Completed!
Running RuboCop...
Inspecting 64 files
................................................................

64 files inspected, no offenses detected
```

But, since using 6.0.0 in the tests, I'm stuck..

```
~/c/windows ❯❯❯ chef gem install foodcritic
Fetching: foodcritic-6.0.0.gem (100%)
Successfully installed foodcritic-6.0.0
1 gem installed
~/c/windows ❯❯❯ chef exec rake style
Starting Foodcritic linting...
FC058: Library provider declares use_inline_resources and declares #action_<name> methods: /Users/shoekstra/cookbooks/windows/libraries/windows_package.rb:10
```

This is as close as I can get to clearing the warnings, seems it's something in `Chef::Provider::LWRPBase` that is causing this.  Was tempted to filter out `xx provider declares use_inline_resources and declares #action_<name> methods` warnings as use_inline_resources could have adverse effects but tried not to do this.

**Comment by shoekstra** [comment]
Forgot to add, the passing tests for foodcritic 5.0.0 worked on the first commit; the second commit was an attempt to make the tests pass using 6.0.0.

**Comment by mwrock** [comment]
oh man so sorry. Looks like your build is the lucky recipient of the new chef-dk 0.11.0. Thanks so much for getting this up to snuff with ruboco 0.37. I'll submit a separate PR to fix foodcritic.

**Comment by mwrock** [comment]
closing this. I pulled your commits into #341 and added an ignore for that rubocop warning on a deprecated provider. Thanks!!

**Pull request closed without merging**
