### PR TITLE
Separating assignments to code_script and guard_script as they should…

### PR DESCRIPTION
**Pull request by ruicovelo**
Separating assignments to code_script and guard_script as they should be different scripts and not hold the same reference.

### CODE REVIEW

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.getchef.com/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## GitHub Users Who Are Not Authorized To Contribute

The following GitHub users do not appear to have signed a CLA:

* @ruicovelo

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by mwrock** [comment]
I believe this PR is inspired by #291. I think your concern there was that the concatenation of the guard_script and code_script.

Here you are referring to a assignment by reference issue. So if they are unrelated thats fine but I don't think the reference issue exits here. cert_script just returns a string and both guard_script and code_script are assigned to that string. Later changing guard_script will not impact code_script.

However, I might be totally missing the issue here. Can you shed more detail?

**Comment by ruicovelo** [comment]
Sure. The assignment is by reference if you do it like this: code_script=guard_script=<anything>

Here is an example. Notice the object_id:

> ruby --version
ruby 2.0.0p645 (2015-04-13) [i386-mingw32]

> irb --version
irb 0.9.6(09/06/30)

> irb
irb(main):001:0> code_script=guard_script=''
=> ""
irb(main):002:0> code_script.object_id
=> 23843244
irb(main):003:0> guard_script.object_id
=> 23843244
irb(main):004:0> code_script << 'something'
=> "something"
irb(main):005:0> guard_script
=> "something"
irb(main):006:0> guard_script << 'some other thing'
=> "somethingsome other thing"
irb(main):007:0> code_script
=> "somethingsome other thing"
irb(main):008:0>

**Comment by chef-supermarket** [comment]
Hi. Your friendly Curry bot here. Just letting you know that all commit authors have become authorized to contribute. I have added the "Signed CLA" label to this issue so it can easily be found in the future.

**Comment by mwrock** [comment]
ah duh. of course. I was thinking of reassignments and forgot about the concatenation.

**Comment by mwrock** [comment]
You think you can rebase master? I think that will get this to green.

**Comment by ruicovelo** [comment]
Done!

**Comment by mwrock** [comment]
:+1:

Cc @chef/windows-client

**Comment by smurawski** [comment]
:+1:  LGTM

**Pull request merged**
