### PR TITLE
Adds ChefSpec matchers for windows_certificate resources

### PR DESCRIPTION
**Pull request by shoekstra**

### CODE REVIEW

**Comment by mwrock** [comment]
I like it. You just need to offer solace to rubocop.

**Comment by shoekstra** [comment]
Fixed locally, but that opens another can of worms...

```
Inspecting 64 files
......C....C.CCC...CCC...C.......C..............................

Offenses:

...

64 files inspected, 34 offenses detected
```

I'll open another PR that fixes these.

**Comment by mwrock** [comment]
:+1: #341 fixed the tests. Appveyor still broken because I cant rerun the test

**Comment by smurawski** [comment]
I kicked appveyor :+1:

**Pull request merged**
