### PR TITLE
fix #424

### LINKED ISSUE #424: path resource - should replace / with \
### Cookbook version

2.1.1

### Chef-client version

12.17

### Platform Details

windows 2012r2

### Scenario:

Adding a path created with File.join

``` widows_path ::File.join(domain_path, 'bin') ```

### Steps to Reproduce:

``` widows_path "C:/Foo/Bar" ```

### Expected Result:

A new path component should be added, with the input's forward slashes replaced by backslashes
"C:\Foo\Bar"

### Actual Result:

The path component contains forward slashes, thus it is not working. ( "C:/Foo/Bar")

### PR DESCRIPTION
**Pull request by axos88**
### Description

Paths can now be given in ruby notation or windows notation (forward slashes are now accepted as well)

### Issues Resolved

#424 

### Check List

- [ ] All tests pass. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD>
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable
- [ ] All commits have been signed for the Developer Certificate of Origin. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD>

### CODE REVIEW

**Comment by tas50** [comment]
Can you add tests for this. We already have a test recipe for the path resource. Just make sure we get a path of the format this fixes added there.

**Comment by axos88** [comment]
Will do.

**Comment by axos88** [comment]
The lint error is not in any modified files...

**Comment by tas50** [comment]
Thanks for getting those tests updated. This is probably going to help a lot of people that get confused why the path resource doesn't work how they'd expect

**Comment by axos88** [comment]
Me being one of them :)

**Pull request merged**
