### PR TITLE
Restore Windows 2008 support for windows_feature

### PR DESCRIPTION
**Pull request by shoekstra**
### Description

Fixes Windows 2008 compatibility for the `windows_feature` resource.

### Issues Resolved

`windows_feature` at the moment breaks as `Install-WindowsFeature` does not exist in Windows 2008, 

### Check List

- [x] All tests pass. See https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD
- [x] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable
- [x] The CLA has been signed. See https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD

### CODE REVIEW

**Comment by shoekstra** [comment]
An unrelated test causes this to fail (No acceptance tests for Windows 2008 it seems):

```
           ================================================================================
           Error executing action `install` on resource 'windows_package[Mercurial 3.6.1 (64-bit)]'
           ================================================================================
           
           SocketError
           -----------
           remote_file[C:\Users\vagrant\AppData\Local\Temp\kitchen\cache\package\Mercurial-3.6.1-x64.exe] (dynamically defined) had an error: SocketError: Error connecting to http://mercurial.selenic.com/release/windows/Mercurial-3.6.1-x64.exe - getaddrinfo: No such host is known. 
```

I'll create a separate PR to address this.

**Comment by shoekstra** [comment]
Fixed, ready to merge 😄 ?

**Comment by mwrock** [comment]
:+1:  LGTM

**Comment by smurawski** [comment]
👍

**Comment by smurawski** [comment]
@shoekstra Released in v1.44.0

**Comment by shoekstra** [comment]
@mwrock @smurawski: awesome, thanks guys!

**Pull request merged**
